#!/usr/bin/env bash
# 	wget http://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel
#	chmod 755 parallel
#	sudo ln -s ./parallel /usr/local/bin/parallel
#
# @author
#	Bharath Sankaran
#	Computational Motor Control and Learning Laboratory
#	University of Southern California
#	Los Angeles, CA 90089
#	12/04/2012
#
#


# object names:
declare -a ONAMES=(axe bigbox broom brush flowerspray gastank handlebottle heavyranch pan pipe shovel spadefork spraybottle watercan wreckbar apples bathroomkit bottles cups glasses vases)

DATABASE_DIR=$(rospack find vision_module)/../database

for oidx in "${!ONAMES[@]}"; do
	mv $DATABASE_DIR/cloud_data/${ONAMES[$oidx]}_views/${ONAMES[$oidx]}_complete.pcd $DATABASE_DIR/pcd_models/${ONAMES[$oidx]}_complete.pcd
done
